name: SmartLogix CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  IMAGE_TAG: latest

jobs:

  build-java:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - service: ms-auth
            path: proyecto/microservicios/ms-auth

          - service: ms-orders
            path: proyecto/microservicios/ms-orders

          - service: api-gateway
            path: proyecto/api-gateway

    steps:

      - uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Compilar proyecto
        working-directory: ${{ matrix.path }}
        run: mvn clean package -DskipTests


  build-frontend:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar PNPM
        run: |
          corepack enable

      - name: Instalar dependencias
        working-directory: proyecto/frontend
        run: pnpm install

      - name: Build Frontend
        working-directory: proyecto/frontend
        run: pnpm build


  docker-build-push:

    needs:
      - build-java
      - build-frontend

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:

          - name: ms-auth
            path: proyecto/microservicios/ms-auth

          - name: ms-orders
            path: proyecto/microservicios/ms-orders

          - name: api-gateway
            path: proyecto/api-gateway

          - name: frontend
            path: proyecto/frontend

    steps:

      - uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${{ matrix.name }}:${{ env.IMAGE_TAG }} \
          ${{ matrix.path }}

      - name: Push Docker Image
        run: |
          docker push \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${{ matrix.name }}:${{ env.IMAGE_TAG }}